### PR TITLE
Add package.json + build and watch scripts

### LINKED ISSUE #4: Package manager
The project uses typescript to build its files. This is great, but in the readme it is recommended that contributors install typescript globally on their system.

This is a bad practice since the contributor might have two typescript projects on their system with conflicting versions of typescript! 

Of course this also bloats the contributor's system. It is generally a bad practice.

### Proposed fix:

Using NPM or Yarn, add a `package.json` that requires [typescript](https://www.npmjs.com/package/typescript) as a dev dependency. This way, the contributor can clone the repo, run `yarn install` or `npm install`, and run `npm build` or `yarn build` which triggers the build script defined in the `package.json`.

### PR DESCRIPTION
**Pull request by FrontEndCoffee**
This PR fixes #4 . I also took the liberty of updating the README so that everything is clear for everyone.

Note: the `yarn.lock` was added so that everyone can install the exact versions of packages that have been proven to work.

### CODE REVIEW

**Comment by Lucky-Loek** [comment]
I believe the previously merged PR (#3 ) creates this conflict.

**Comment by FrontEndCoffee** [comment]
One sec, I'll fix it

**Comment by FrontEndCoffee** [comment]
@Lucky-Loek Fixed

**Comment by Lucky-Loek** [comment]
Awesome, thanks! 

One last question: does the `tsc` command in the `package.json` file automa(t/g)ically use the project-defined TypeScript compiler? Seems to me that need to be added to the path variables of the user.

**Comment by FrontEndCoffee** [comment]
@Lucky-Loek When using binaries like `tsc` in the `scripts` section of the `package.json`, npm/yarn will automatically resolve that to a package that has been locally installed in that project. So that would be the `node_modules` folder. 

This is why this is a great way of working; you can use the binaries without relying on developers to add them to their global path!

**Comment by Lucky-Loek** [comment]
Guess you learn something every day!

**Pull request merged**
